"""create items table

Revision ID: a7c56db0f0be
Revises: 
Create Date: 2025-07-02 17:37:05.839678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c56db0f0be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.String(length=255), nullable=False, comment='拾得物ID。yy-mm-dd-h-nn形式'),
    sa.Column('facility_id', sa.Integer(), nullable=False, comment='登録施設ID'),
    sa.Column('category_large', sa.String(length=100), nullable=True, comment='分類(大)'),
    sa.Column('category_medium', sa.String(length=100), nullable=True, comment='分類(中)'),
    sa.Column('claims_ownership', sa.Boolean(), nullable=False, comment='所有権主張'),
    sa.Column('claims_reward', sa.Boolean(), nullable=False, comment='報労金請求'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
